image: 
  file: .gitpod.Dockerfile
ports: 
  - onOpen: open-browser
    port: 8080
    visibility: public 
tasks: 
  - init: pip install -r requirements.txt
    command: flask init & flask run
  - init: npm install
vscode:
  extensions:
    - ms-python.python
    - alexcvzz.vscode-sqlite